package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"

	"github.com/spf13/cobra"
)

func newDevCmd() *cobra.Command {
	var port int
	var airConfig string
	var noAir bool

	cmd := &cobra.Command{
		Use:   "dev",
		Short: "Start development server with hot reload",
		Long: `Start development server with automatic code generation and hot reload.

Uses Air for hot reload if available, falls back to basic file watcher.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDev(port, airConfig, noAir)
		},
	}

	cmd.Flags().IntVar(&port, "port", 0, "Server port (default: from .glibrc or 8080)")
	cmd.Flags().StringVar(&airConfig, "air-config", ".air.toml", "Air config file")
	cmd.Flags().BoolVar(&noAir, "no-air", false, "Disable Air, use basic file watcher")

	return cmd
}

func runDev(port int, airConfig string, noAir bool) error {
	// Check if .glibrc exists
	if _, err := os.Stat(".glibrc"); os.IsNotExist(err) {
		return fmt.Errorf("no .glibrc found - run 'glib init' first")
	}

	// Load config for port
	cfg, err := loadGlibConfig()
	if err != nil {
		return fmt.Errorf("failed to load .glibrc: %w", err)
	}

	// Use port from flag, or from config, or default to 8080
	if port == 0 {
		if cfg.Dev.Port != 0 {
			port = cfg.Dev.Port
		} else {
			port = 8080
		}
	}

	fmt.Printf("🚀 Starting Glib dev server on port %d\n\n", port)

	// Run initial generation
	fmt.Println("📦 Running initial code generation...")
	if err := runGenerate(&generateOptions{dir: ".", verbose: false}); err != nil {
		return fmt.Errorf("initial generation failed: %w", err)
	}
	fmt.Println("✅ Initial generation complete\n")

	// Generate .air.toml if it doesn't exist
	if _, err := os.Stat(airConfig); os.IsNotExist(err) && !noAir {
		fmt.Printf("📝 Generating %s...\n", airConfig)
		if err := generateAirConfig(airConfig, cfg); err != nil {
			return fmt.Errorf("failed to generate Air config: %w", err)
		}
		fmt.Printf("✅ Generated %s\n\n", airConfig)
	}

	// Check if Air is installed
	if !noAir {
		if _, err := exec.LookPath("air"); err != nil {
			fmt.Println("⚠️  Air not found in PATH")
			fmt.Println("   Install with: go install github.com/cosmtrek/air@latest")
			fmt.Println("   Falling back to basic mode (no hot reload)\n")
			noAir = true
		}
	}

	if noAir {
		// Basic mode - just build and run (no hot reload)
		return runBasicMode(port)
	}

	// Start Air
	fmt.Println("🔥 Starting Air hot reload...")
	fmt.Println("   Watching for file changes...")
	fmt.Println("   Press Ctrl+C to stop\n")

	airCmd := exec.Command("air", "-c", airConfig)
	airCmd.Stdout = os.Stdout
	airCmd.Stderr = os.Stderr
	airCmd.Stdin = os.Stdin
	airCmd.Env = append(os.Environ(), fmt.Sprintf("APP_PORT=%d", port))

	return airCmd.Run()
}

func runBasicMode(port int) error {
	fmt.Println("🔨 Building application...")

	// Build the app
	buildCmd := exec.Command("go", "build", "-o", "./tmp/main", ".")
	buildCmd.Stdout = os.Stdout
	buildCmd.Stderr = os.Stderr

	if err := buildCmd.Run(); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}

	fmt.Printf("✅ Build complete\n\n")
	fmt.Printf("🚀 Starting server on port %d...\n", port)
	fmt.Println("   (No hot reload in basic mode - restart manually after changes)\n")

	// Run the app
	runCmd := exec.Command("./tmp/main")
	runCmd.Stdout = os.Stdout
	runCmd.Stderr = os.Stderr
	runCmd.Stdin = os.Stdin
	runCmd.Env = append(os.Environ(), fmt.Sprintf("APP_PORT=%d", port))

	return runCmd.Run()
}

func generateAirConfig(path string, cfg *glibConfig) error {
	// Ensure tmp directory exists
	if err := os.MkdirAll("tmp", 0755); err != nil {
		return fmt.Errorf("failed to create tmp directory: %w", err)
	}

	outputDir := "generated"
	if cfg.Generate.Output != "" {
		outputDir = cfg.Generate.Output
	}

	// Get the glib binary path
	glibCmd := "glib"
	if _, err := exec.LookPath("glib"); err != nil {
		// If glib is not in PATH, use go run as fallback
		// Note: This requires the project's go.mod to have glib as dependency
		glibCmd = "go run github.com/azizndao/glib/cmd/glib@latest"
	}

	airToml := fmt.Sprintf(`# Air configuration for Glib hot reload
# Generated by 'glib dev' - you can customize this file
# 
# NOTE: Make sure 'glib' is in your PATH, or install it with:
#   go install github.com/azizndao/glib/cmd/glib@latest

root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "%s generate && go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", "%s"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
`, glibCmd, outputDir)

	return os.WriteFile(path, []byte(airToml), 0644)
}

func loadGlibConfig() (*glibConfig, error) {
	data, err := os.ReadFile(".glibrc")
	if err != nil {
		return nil, err
	}

	var cfg glibConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}

	return &cfg, nil
}
