package generator

import (
	"fmt"
	"strings"
)

// generateBootstrap generates the main bootstrap file (glib.gen.go)
func (g *Generator) generateBootstrap() (string, error) {
	var b strings.Builder

	// Package and imports
	b.WriteString(fmt.Sprintf("// Code generated by glib. DO NOT EDIT.\n\n"))
	b.WriteString(fmt.Sprintf("package %s\n\n", g.pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString(")\n\n")

	// Bootstrap function
	b.WriteString("// Bootstrap initializes the application and returns the HTTP handler\n")
	b.WriteString("func Bootstrap(ctx context.Context) (http.Handler, error) {\n")
	b.WriteString("\t// Initialize DI container\n")
	b.WriteString("\tcontainer, err := initContainer(ctx)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// Create router\n")
	b.WriteString("\trouter := http.NewServeMux()\n\n")
	b.WriteString("\t// Register routes\n")
	b.WriteString("\tif err := registerRoutes(router, container); err != nil {\n")
	b.WriteString("\t\treturn nil, err\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// Apply global middleware (if any)\n")
	b.WriteString("\thandler := applyMiddleware(router, container)\n\n")
	b.WriteString("\treturn handler, nil\n")
	b.WriteString("}\n")

	return b.String(), nil
}
