package generator

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/azizndao/glib/internal/scanner"
)

// ConfigGenerator generates configuration loader code
type ConfigGenerator struct {
	project       *scanner.Project
	targetPackage string // Package where code will be generated (e.g., "generated")
}

// NewConfigGenerator creates a new config generator
func NewConfigGenerator(project *scanner.Project, targetPackage string) *ConfigGenerator {
	return &ConfigGenerator{
		project:       project,
		targetPackage: targetPackage,
	}
}

// GenerateConfigLoaderForPackage generates loadXxxConfig functions for all configs
func (g *ConfigGenerator) GenerateConfigLoaderForPackage(configPackagePath string) (string, error) {
	if len(g.project.Configs) == 0 {
		return "", nil
	}

	// Collect all configs with their processed data
	type configData struct {
		ConfigPackageName string
		ConfigName        string
		FunctionName      string
		Fields            []map[string]interface{}
	}

	var configs []configData
	needsTime := false
	needsURL := false

	// Process each config
	for _, cfg := range g.project.Configs {
		// Flatten nested fields for easier template processing
		fields := g.flattenFields(cfg.Fields, "")

		// Detect if we need special imports
		for _, field := range fields {
			typeInfo := field["Type"].(*scanner.TypeInfo)
			if typeInfo.FullName == "time.Duration" {
				needsTime = true
			}
			if typeInfo.FullName == "url.URL" || typeInfo.FullName == "*url.URL" {
				needsURL = true
			}
		}

		configs = append(configs, configData{
			ConfigPackageName: cfg.PackageName,
			ConfigName:        cfg.Name,
			FunctionName:      "load" + cfg.Name,
			Fields:            fields,
		})
	}

	// Generate single file with all configs
	var buf bytes.Buffer
	err := templates.ExecuteTemplate(&buf, "config.tmpl", map[string]interface{}{
		"PackageName":      g.targetPackage,
		"ConfigImportPath": configPackagePath,
		"Configs":          configs,
		"NeedsTime":        needsTime,
		"NeedsURL":         needsURL,
	})
	if err != nil {
		return "", err
	}

	return buf.String(), nil
}

// flattenFields recursively flattens nested config fields
func (g *ConfigGenerator) flattenFields(fields []*scanner.ConfigField, parentPath string) []map[string]interface{} {
	var result []map[string]any

	for _, field := range fields {
		if field.IsNested && len(field.Fields) > 0 {
			// Recursively flatten nested fields
			nestedPath := parentPath + field.Name + "."
			result = append(result, g.flattenFields(field.Fields, nestedPath)...)
		} else {
			// Add leaf field
			result = append(result, map[string]interface{}{
				"Name":         field.Name,
				"ParentPath":   parentPath,
				"Type":         field.Type,
				"EnvName":      field.EnvName,
				"DefaultValue": field.DefaultValue,
				"Required":     field.Required,
			})
		}
	}

	return result
}

// GenerateEnvExample generates a .env.example file
func (g *ConfigGenerator) GenerateEnvExample() (string, error) {
	if len(g.project.Configs) == 0 {
		return "", nil
	}

	var buf strings.Builder
	buf.WriteString("# Environment Variables\n")
	buf.WriteString("# Generated by glib - edit as needed\n\n")

	var generate func([]*scanner.ConfigField, string)
	generate = func(fields []*scanner.ConfigField, section string) {
		if section != "" {
			fmt.Fprintf(&buf, "# %s\n", section)
		}

		for _, field := range fields {
			if field.IsNested && len(field.Fields) > 0 {
				generate(field.Fields, field.Name+" Configuration")
			} else {
				// Write comment
				comment := field.EnvName
				if field.Required {
					comment += " (required)"
				}
				if field.DefaultValue != "" {
					comment += fmt.Sprintf(" [default: %s]", field.DefaultValue)
				}
				fmt.Fprintf(&buf, "%s=%s\n", field.EnvName, field.DefaultValue)
			}
		}
		buf.WriteString("\n")
	}

	// Generate for all configs
	for _, cfg := range g.project.Configs {
		fmt.Fprintf(&buf, "# %s\n", cfg.Name)
		generate(cfg.Fields, "")
	}

	return buf.String(), nil
}
