package generator

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/azizndao/glib/internal/scanner"
)

// ConfigGenerator generates configuration loader code
type ConfigGenerator struct {
	project       *scanner.Project
	targetPackage string // (e.g., "generated")
}

func NewConfigGenerator(project *scanner.Project, targetPackage string) *ConfigGenerator {
	return &ConfigGenerator{
		project:       project,
		targetPackage: targetPackage,
	}
}

// GenerateConfigLoaderForPackage generates loadXxxConfig functions for all configs
func (g *ConfigGenerator) GenerateConfigLoaderForPackage(configPackagePath string) (string, error) {
	if len(g.project.Configs) == 0 {
		return "", nil
	}

	// Collect all configs with their processed data
	type configData struct {
		ConfigPackageName string
		ConfigName        string
		FunctionName      string
		Fields            []map[string]any
		NeedsErrorVar     bool
		HasRequiredFields bool
	}

	var configs []configData
	needsTime := false
	needsURL := false

	// Sort configs alphabetically for deterministic output
	sortedConfigs := make([]*scanner.Config, len(g.project.Configs))
	copy(sortedConfigs, g.project.Configs)
	sort.Slice(sortedConfigs, func(i, j int) bool {
		return sortedConfigs[i].Name < sortedConfigs[j].Name
	})

	for _, cfg := range sortedConfigs {
		// Flatten nested fields for easier template processing
		fields := g.flattenFields(cfg.Fields, "")

		// Detect if we need special imports and variables
		needsErrorVar := false
		hasRequiredFields := false

		for _, field := range fields {
			typeInfo := field["Type"].(*scanner.TypeInfo)

			// Check for special imports
			if typeInfo.FullName == "time.Duration" {
				needsTime = true
			}
			if typeInfo.FullName == "url.URL" || typeInfo.FullName == "*url.URL" {
				needsURL = true
			}

			// Check if this field needs error handling
			if g.needsErrorHandling(typeInfo) {
				needsErrorVar = true
			}

			// Check if any field is required
			if required, ok := field["Required"].(bool); ok && required {
				hasRequiredFields = true
			}
		}

		configs = append(configs, configData{
			ConfigPackageName: cfg.PackageName,
			ConfigName:        cfg.Name,
			FunctionName:      "load" + cfg.Name,
			Fields:            fields,
			NeedsErrorVar:     needsErrorVar,
			HasRequiredFields: hasRequiredFields,
		})
	}

	// Generate single file with all configs
	var buf bytes.Buffer
	err := templates.ExecuteTemplate(&buf, "config.templ", map[string]any{
		"PackageName":      g.targetPackage,
		"ConfigImportPath": configPackagePath,
		"Configs":          configs,
		"NeedsTime":        needsTime,
		"NeedsURL":         needsURL,
	})
	if err != nil {
		return "", err
	}

	return buf.String(), nil
}

// flattenFields recursively flattens nested config fields
func (g *ConfigGenerator) flattenFields(fields []*scanner.ConfigField, parentPath string) []map[string]any {
	var result []map[string]any

	for _, field := range fields {
		if field.IsNested && len(field.Fields) > 0 {
			// Recursively flatten nested fields
			nestedPath := parentPath + field.Name + "."
			result = append(result, g.flattenFields(field.Fields, nestedPath)...)
		} else {
			// Add leaf field
			result = append(result, map[string]any{
				"Name":         field.Name,
				"ParentPath":   parentPath,
				"Type":         field.Type,
				"EnvName":      field.EnvName,
				"DefaultValue": field.DefaultValue,
				"Required":     field.Required,
			})
		}
	}

	return result
}

// needsErrorHandling returns true if the type requires error handling in env parsing
func (g *ConfigGenerator) needsErrorHandling(typeInfo *scanner.TypeInfo) bool {
	// These types use functions that return (value, error)
	switch typeInfo.Name {
	case "int", "int64", "uint64", "bool", "float64":
		return true
	}

	// Check for special types
	switch typeInfo.FullName {
	case "time.Duration", "url.URL", "*url.URL":
		return true
	}

	return false
}

// GenerateEnvExample generates a .env.example file
func (g *ConfigGenerator) GenerateEnvExample() (string, error) {
	if len(g.project.Configs) == 0 {
		return "", nil
	}

	var buf strings.Builder
	buf.WriteString("# Environment Variables\n")
	buf.WriteString("# Generated by glib - edit as needed\n\n")

	var generate func([]*scanner.ConfigField, string)
	generate = func(fields []*scanner.ConfigField, section string) {
		if section != "" {
			fmt.Fprintf(&buf, "# %s\n", section)
		}

		for _, field := range fields {
			if field.IsNested && len(field.Fields) > 0 {
				generate(field.Fields, field.Name+" Configuration")
			} else {
				fmt.Fprintf(&buf, "%s=%s\n", field.EnvName, field.DefaultValue)
			}
		}
		buf.WriteString("\n")
	}

	// Sort configs alphabetically for deterministic output
	sortedConfigs := make([]*scanner.Config, len(g.project.Configs))
	copy(sortedConfigs, g.project.Configs)
	sort.Slice(sortedConfigs, func(i, j int) bool {
		return sortedConfigs[i].Name < sortedConfigs[j].Name
	})

	// Generate for all configs
	for _, cfg := range sortedConfigs {
		fmt.Fprintf(&buf, "# %s\n", cfg.Name)
		generate(cfg.Fields, "")
	}

	return buf.String(), nil
}
