package generator

import (
	"fmt"
	"strings"

	"github.com/goyave/glib/v2/internal/scanner"
)

// generateDI generates the DI container (di.gen.go)
func (g *Generator) generateDI() (string, error) {
	var b strings.Builder

	// Package and imports
	b.WriteString("// Code generated by glib. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", g.pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"fmt\"\n")

	// Collect all unique imports from providers and controllers
	imports := g.collectImports()
	for _, imp := range imports {
		b.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}

	b.WriteString(")\n\n")

	// Container struct
	b.WriteString("// container holds all dependencies\n")
	b.WriteString("type container struct {\n")
	b.WriteString("\tctx context.Context\n")

	// Add fields for all providers
	for _, prov := range g.project.Providers {
		fieldName := g.providerFieldName(prov)
		typeName := g.typeString(prov.ReturnType)
		b.WriteString(fmt.Sprintf("\t%s %s\n", fieldName, typeName))
	}

	// Add fields for all controllers
	for _, ctrl := range g.project.Controllers {
		fieldName := g.controllerFieldName(ctrl)
		b.WriteString(fmt.Sprintf("\t%s *%s.%s\n", fieldName, ctrl.PackageName, ctrl.Name))
	}

	// Add fields for all middleware
	for _, mw := range g.project.Middleware {
		fieldName := g.middlewareFieldName(mw)
		b.WriteString(fmt.Sprintf("\t%s func(http.Handler) http.Handler\n", fieldName))
	}

	b.WriteString("}\n\n")

	// initContainer function
	b.WriteString("// initContainer initializes the DI container\n")
	b.WriteString("func initContainer(ctx context.Context) (*container, error) {\n")
	b.WriteString("\tc := &container{ctx: ctx}\n\n")

	// Initialize providers (in dependency order - simplified for now)
	b.WriteString("\t// Initialize providers\n")
	for _, prov := range g.project.Providers {
		if err := g.generateProviderInit(&b, prov); err != nil {
			return "", err
		}
	}

	// Initialize controllers
	b.WriteString("\n\t// Initialize controllers\n")
	for _, ctrl := range g.project.Controllers {
		g.generateControllerInit(&b, ctrl)
	}

	// Initialize middleware
	b.WriteString("\n\t// Initialize middleware\n")
	for _, mw := range g.project.Middleware {
		g.generateMiddlewareInit(&b, mw)
	}

	b.WriteString("\n\treturn c, nil\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// generateProviderInit generates initialization code for a provider
func (g *Generator) generateProviderInit(b *strings.Builder, prov *scanner.Provider) error {
	fieldName := g.providerFieldName(prov)

	// Build dependency arguments
	var args []string
	for _, dep := range prov.Dependencies {
		// Find the provider field that provides this dependency
		depFieldName := g.findProviderForType(dep.Type)
		if depFieldName != "" {
			args = append(args, "c."+depFieldName)
		}
	}

	// Generate call
	b.WriteString(fmt.Sprintf("\tvar err error\n"))
	b.WriteString(fmt.Sprintf("\tc.%s, err = %s.%s(%s)\n",
		fieldName,
		prov.PackageName,
		prov.FunctionName,
		strings.Join(args, ", ")))
	b.WriteString("\tif err != nil {\n")
	b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"failed to initialize %s: %%w\", err)\n", prov.Name))
	b.WriteString("\t}\n\n")

	return nil
}

// generateControllerInit generates initialization code for a controller
func (g *Generator) generateControllerInit(b *strings.Builder, ctrl *scanner.Controller) {
	fieldName := g.controllerFieldName(ctrl)

	b.WriteString(fmt.Sprintf("\tc.%s = &%s.%s{\n", fieldName, ctrl.PackageName, ctrl.Name))

	// Inject dependencies
	for _, field := range ctrl.Fields {
		providerField := g.findProviderForType(field.Type)
		if providerField != "" {
			b.WriteString(fmt.Sprintf("\t\t%s: c.%s,\n", field.Name, providerField))
		}
	}

	b.WriteString("\t}\n\n")
}

// generateMiddlewareInit generates initialization code for middleware
func (g *Generator) generateMiddlewareInit(b *strings.Builder, mw *scanner.Middleware) {
	fieldName := g.middlewareFieldName(mw)

	// Build dependency arguments
	var args []string
	for _, dep := range mw.Dependencies {
		providerField := g.findProviderForType(dep.Type)
		if providerField != "" {
			args = append(args, "c."+providerField)
		}
	}

	b.WriteString(fmt.Sprintf("\tc.%s = %s.%s(%s)\n",
		fieldName,
		mw.PackageName,
		mw.FunctionName,
		strings.Join(args, ", ")))
}

// Helper functions

func (g *Generator) providerFieldName(prov *scanner.Provider) string {
	// Convert NewDatabase -> database
	name := prov.FunctionName
	if strings.HasPrefix(name, "New") {
		name = name[3:]
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func (g *Generator) controllerFieldName(ctrl *scanner.Controller) string {
	return strings.ToLower(ctrl.Name[:1]) + ctrl.Name[1:]
}

func (g *Generator) middlewareFieldName(mw *scanner.Middleware) string {
	return mw.Name + "Middleware"
}

func (g *Generator) findProviderForType(typeInfo *scanner.TypeInfo) string {
	if typeInfo == nil {
		return ""
	}

	// Find a provider that returns this type
	for _, prov := range g.project.Providers {
		if prov.ReturnType != nil && prov.ReturnType.FullName == typeInfo.FullName {
			return g.providerFieldName(prov)
		}
	}

	return ""
}

func (g *Generator) typeString(typeInfo *scanner.TypeInfo) string {
	if typeInfo == nil {
		return "interface{}"
	}
	return typeInfo.FullName
}

func (g *Generator) collectImports() []string {
	seen := make(map[string]bool)
	var imports []string

	// Add imports from controllers
	for _, ctrl := range g.project.Controllers {
		if !seen[ctrl.PackagePath] && ctrl.PackagePath != g.pkgName {
			seen[ctrl.PackagePath] = true
			imports = append(imports, ctrl.PackagePath)
		}
	}

	// Add imports from providers
	for _, prov := range g.project.Providers {
		if !seen[prov.PackagePath] && prov.PackagePath != g.pkgName {
			seen[prov.PackagePath] = true
			imports = append(imports, prov.PackagePath)
		}
	}

	// Add imports from middleware
	for _, mw := range g.project.Middleware {
		if !seen[mw.PackagePath] && mw.PackagePath != g.pkgName {
			seen[mw.PackagePath] = true
			imports = append(imports, mw.PackagePath)
		}
	}

	// Add net/http for middleware
	if !seen["net/http"] {
		imports = append(imports, "net/http")
	}

	return imports
}
