package generator

import (
	"fmt"
	"strings"
)

// generateErrors generates error handling helpers (errors.gen.go)
func (g *Generator) generateErrors() (string, error) {
	var b strings.Builder

	// Package and imports
	b.WriteString("// Code generated by glib. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", g.pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString(fmt.Sprintf("\t\"%s/pkg/errs\"\n", g.project.Module))
	b.WriteString(")\n\n")

	// writeJSON helper
	b.WriteString("// writeJSON writes a JSON response\n")
	b.WriteString("func writeJSON(w http.ResponseWriter, status int, data interface{}) {\n")
	b.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\tw.WriteHeader(status)\n")
	b.WriteString("\tif data != nil {\n")
	b.WriteString("\t\tjson.NewEncoder(w).Encode(data)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// writeError helper
	b.WriteString("// writeError writes an error response\n")
	b.WriteString("func writeError(w http.ResponseWriter, err error) {\n")
	b.WriteString("\tvar glibErr *errs.Error\n")
	b.WriteString("\tif errors.As(err, &glibErr) {\n")
	b.WriteString("\t\t// Structured glib error\n")
	b.WriteString("\t\twriteJSON(w, glibErr.Code().HTTPStatus(), map[string]interface{}{\n")
	b.WriteString("\t\t\t\"error\": map[string]interface{}{\n")
	b.WriteString("\t\t\t\t\"code\":    glibErr.Code(),\n")
	b.WriteString("\t\t\t\t\"message\": glibErr.Message(),\n")
	b.WriteString("\t\t\t\t\"meta\":    glibErr.Meta(),\n")
	b.WriteString("\t\t\t},\n")
	b.WriteString("\t\t})\n")
	b.WriteString("\t\treturn\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\t// Generic error\n")
	b.WriteString("\twriteJSON(w, http.StatusInternalServerError, map[string]interface{}{\n")
	b.WriteString("\t\t\"error\": map[string]interface{}{\n")
	b.WriteString("\t\t\t\"code\":    \"internal_error\",\n")
	b.WriteString("\t\t\t\"message\": err.Error(),\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t})\n")
	b.WriteString("}\n")

	return b.String(), nil
}
