package generator

import (
	"fmt"
	"strings"

	"github.com/goyave/glib/v2/internal/scanner"
)

// generateParsers generates request/response parsers for each handler (parsers.gen.go)
func (g *Generator) generateParsers() (string, error) {
	var b strings.Builder

	// Package and imports
	b.WriteString("// Code generated by glib. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", g.pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"github.com/google/uuid\"\n")

	// Add package imports
	imports := g.collectImports()
	for _, imp := range imports {
		b.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}

	b.WriteString(")\n\n")

	// Generate handler wrappers for each handler
	for _, ctrl := range g.project.Controllers {
		for _, handler := range ctrl.Handlers {
			if err := g.generateHandlerWrapper(&b, ctrl, handler); err != nil {
				return "", err
			}
		}
	}

	return b.String(), nil
}

// generateHandlerWrapper generates a wrapper function for a handler
func (g *Generator) generateHandlerWrapper(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler) error {
	wrapperName := g.handlerWrapperName(ctrl, handler)
	ctrlField := g.controllerFieldName(ctrl)

	b.WriteString(fmt.Sprintf("// %s wraps %s.%s\n", wrapperName, ctrl.Name, handler.Name))
	b.WriteString(fmt.Sprintf("func %s(c *container) http.HandlerFunc {\n", wrapperName))
	b.WriteString("\treturn func(w http.ResponseWriter, r *http.Request) {\n")

	sig := handler.Signature

	// Handle different patterns
	switch sig.Pattern {
	case 1, 2:
		// Pattern 1-2: Raw HTTP (w, r)
		g.generateRawHTTPHandler(b, ctrl, handler, ctrlField)
	case 3, 4, 5:
		// Pattern 3-5: Context only, no request body
		g.generateContextOnlyHandler(b, ctrl, handler, ctrlField)
	case 6:
		// Pattern 6: Context + Request body
		g.generateContextRequestHandler(b, ctrl, handler, ctrlField)
	case 7:
		// Pattern 7: Context + Path param
		g.generateContextPathParamHandler(b, ctrl, handler, ctrlField)
	case 8:
		// Pattern 8: Context + Path param + Request body
		g.generateContextPathParamRequestHandler(b, ctrl, handler, ctrlField)
	case 9:
		// Pattern 9: Context + Multiple path params + Request body
		g.generateContextMultiParamRequestHandler(b, ctrl, handler, ctrlField)
	}

	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	return nil
}

// generateRawHTTPHandler generates handler for Pattern 1-2
func (g *Generator) generateRawHTTPHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString(fmt.Sprintf("\t\tc.%s.%s(w, r)\n", ctrlField, handler.Name))
}

// generateContextOnlyHandler generates handler for Pattern 3-5
func (g *Generator) generateContextOnlyHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString("\t\tctx := r.Context()\n")

	sig := handler.Signature
	if sig.Pattern == 3 {
		// No return value
		b.WriteString(fmt.Sprintf("\t\tc.%s.%s(ctx)\n", ctrlField, handler.Name))
		b.WriteString("\t\tw.WriteHeader(http.StatusNoContent)\n")
	} else if sig.Pattern == 4 {
		// Returns error only
		b.WriteString(fmt.Sprintf("\t\tif err := c.%s.%s(ctx); err != nil {\n", ctrlField, handler.Name))
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tw.WriteHeader(http.StatusNoContent)\n")
	} else {
		// Returns response + error
		b.WriteString(fmt.Sprintf("\t\tresp, err := c.%s.%s(ctx)\n", ctrlField, handler.Name))
		b.WriteString("\t\tif err != nil {\n")
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\twriteJSON(w, http.StatusOK, resp)\n")
	}
}

// generateContextRequestHandler generates handler for Pattern 6
func (g *Generator) generateContextRequestHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString("\t\tctx := r.Context()\n\n")
	b.WriteString("\t\t// Parse request body\n")
	b.WriteString(fmt.Sprintf("\t\tvar req %s\n", handler.Signature.RequestType.FullName))
	b.WriteString("\t\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n")
	b.WriteString("\t\t\twriteError(w, err)\n")
	b.WriteString("\t\t\treturn\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString(fmt.Sprintf("\t\tresp, err := c.%s.%s(ctx, req)\n", ctrlField, handler.Name))
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\twriteError(w, err)\n")
	b.WriteString("\t\t\treturn\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\twriteJSON(w, http.StatusOK, resp)\n")
}

// generateContextPathParamHandler generates handler for Pattern 7
func (g *Generator) generateContextPathParamHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString("\t\tctx := r.Context()\n\n")

	// Parse path parameters
	for _, param := range handler.Signature.PathParams {
		g.generatePathParamParsing(b, param)
	}

	b.WriteString(fmt.Sprintf("\t\tresp, err := c.%s.%s(ctx, %s)\n",
		ctrlField, handler.Name, handler.Signature.PathParams[0].Name))
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\twriteError(w, err)\n")
	b.WriteString("\t\t\treturn\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\twriteJSON(w, http.StatusOK, resp)\n")
}

// generateContextPathParamRequestHandler generates handler for Pattern 8
func (g *Generator) generateContextPathParamRequestHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString("\t\tctx := r.Context()\n\n")

	// Parse path parameters
	for _, param := range handler.Signature.PathParams {
		g.generatePathParamParsing(b, param)
	}

	// Parse request body
	b.WriteString("\t\t// Parse request body\n")
	b.WriteString(fmt.Sprintf("\t\tvar req %s\n", handler.Signature.RequestType.FullName))
	b.WriteString("\t\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n")
	b.WriteString("\t\t\twriteError(w, err)\n")
	b.WriteString("\t\t\treturn\n")
	b.WriteString("\t\t}\n\n")

	b.WriteString(fmt.Sprintf("\t\tresp, err := c.%s.%s(ctx, %s, req)\n",
		ctrlField, handler.Name, handler.Signature.PathParams[0].Name))
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\twriteError(w, err)\n")
	b.WriteString("\t\t\treturn\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\twriteJSON(w, http.StatusOK, resp)\n")
}

// generateContextMultiParamRequestHandler generates handler for Pattern 9
func (g *Generator) generateContextMultiParamRequestHandler(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) {
	b.WriteString("\t\tctx := r.Context()\n\n")

	// Parse all path parameters
	for _, param := range handler.Signature.PathParams {
		g.generatePathParamParsing(b, param)
	}

	// Parse request body if present
	if handler.Signature.RequestType != nil {
		b.WriteString("\t\t// Parse request body\n")
		b.WriteString(fmt.Sprintf("\t\tvar req %s\n", handler.Signature.RequestType.FullName))
		b.WriteString("\t\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n")
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n\n")
	}

	// Build call arguments
	var args []string
	args = append(args, "ctx")
	for _, param := range handler.Signature.PathParams {
		args = append(args, param.Name)
	}
	if handler.Signature.RequestType != nil {
		args = append(args, "req")
	}

	if handler.Signature.ResponseType != nil {
		b.WriteString(fmt.Sprintf("\t\tresp, err := c.%s.%s(%s)\n",
			ctrlField, handler.Name, strings.Join(args, ", ")))
		b.WriteString("\t\tif err != nil {\n")
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\twriteJSON(w, http.StatusOK, resp)\n")
	} else {
		b.WriteString(fmt.Sprintf("\t\tif err := c.%s.%s(%s); err != nil {\n",
			ctrlField, handler.Name, strings.Join(args, ", ")))
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tw.WriteHeader(http.StatusNoContent)\n")
	}
}

// generatePathParamParsing generates code to parse a path parameter
func (g *Generator) generatePathParamParsing(b *strings.Builder, param *scanner.PathParam) {
	b.WriteString(fmt.Sprintf("\t\t// Parse path parameter: %s\n", param.Name))
	b.WriteString(fmt.Sprintf("\t\t%sStr := r.PathValue(\"%s\")\n", param.Name, param.Name))

	// Handle different types
	if param.Type.PackageName == "uuid" && param.Type.Name == "UUID" {
		b.WriteString(fmt.Sprintf("\t\t%s, err := uuid.Parse(%sStr)\n", param.Name, param.Name))
		b.WriteString("\t\tif err != nil {\n")
		b.WriteString("\t\t\twriteError(w, err)\n")
		b.WriteString("\t\t\treturn\n")
		b.WriteString("\t\t}\n\n")
	} else if param.Type.IsPrimitive {
		// TODO: Add parsing for other primitive types (int, etc.)
		b.WriteString(fmt.Sprintf("\t\t%s := %sStr\n\n", param.Name, param.Name))
	} else {
		// Default: string
		b.WriteString(fmt.Sprintf("\t\t%s := %sStr\n\n", param.Name, param.Name))
	}
}
