package generator

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/azizndao/glib/internal/scanner"
)

// capitalize capitalizes the first letter of a string
func capitalize(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// generateParsers generates request/response parsers for each handler (parsers.gen.go)
func (g *Generator) generateParsers() (string, error) {
	// Collect all controller packages for imports
	usedPackages := make(map[string]bool)
	for _, ctrl := range g.project.Controllers {
		if ctrl.PackagePath != "" && ctrl.PackagePath != g.pkgName {
			usedPackages[ctrl.PackagePath] = true
		}
	}

	// Convert to sorted list for consistent output
	var localImports []string
	for pkgPath := range usedPackages {
		localImports = append(localImports, pkgPath)
	}

	// Start building the file with all potential imports
	// goimports will remove unused ones automatically
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by glib. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", g.pkgName)

	// Write imports - include all potential imports, goimports will clean up
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"strconv\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/azizndao/glib\"\n")
	b.WriteString("\t\"github.com/go-chi/chi/v5\"\n")
	b.WriteString("\t\"github.com/google/uuid\"\n")

	// Add local imports
	if len(localImports) > 0 {
		b.WriteString("\n")
		for _, imp := range localImports {
			fmt.Fprintf(&b, "\t\"%s\"\n", imp)
		}
	}

	b.WriteString(")\n\n")

	// Generate handler wrappers for each handler
	for _, ctrl := range g.project.Controllers {
		for _, handler := range ctrl.Handlers {
			wrapper, err := g.generateHandlerWrapper(ctrl, handler)
			if err != nil {
				return "", err
			}
			b.WriteString(wrapper)
		}
	}

	return b.String(), nil
}

// generateHandlerWrapper generates a wrapper function for a handler
func (g *Generator) generateHandlerWrapper(ctrl *scanner.Controller, handler *scanner.Handler) (string, error) {
	// Use PackageName + Name to ensure uniqueness across multiple controllers
	// e.g., "handlePostControllerIndex", "handleCommentControllerIndex"
	wrapperName := fmt.Sprintf("handle%s%s%s",
		capitalize(ctrl.PackageName),
		ctrl.Name,
		handler.Name)
	ctrlField := g.controllerFieldName(ctrl)

	// Build middleware chain (controller middleware + handler middleware)
	middlewareChain := g.buildMiddlewareChain(ctrl, handler)

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(container *container) http.HandlerFunc {\n", wrapperName)

	// Optimization: For raw HTTP handlers, use method directly (no wrapper needed)
	if handler.Signature.Pattern == scanner.PatternRawHTTP {
		if len(middlewareChain) == 0 {
			// No middleware: return method directly
			fmt.Fprintf(&b, "\treturn container.controllers.%s.%s\n", ctrlField, handler.Name)
		} else {
			// With middleware: wrap method reference
			fmt.Fprintf(&b, "\thandler := http.Handler(http.HandlerFunc(container.controllers.%s.%s))\n\n", ctrlField, handler.Name)

			// Apply middleware chain in reverse order (innermost first)
			for i := len(middlewareChain) - 1; i >= 0; i-- {
				mwFieldName := g.middlewareFieldName(middlewareChain[i])
				fmt.Fprintf(&b, "\thandler = container.middleware.%s(handler)\n", mwFieldName)
			}

			b.WriteString("\n\treturn handler.ServeHTTP\n")
		}
		b.WriteString("}\n\n")
		return b.String(), nil
	}

	// For Result[T] handlers, we need the wrapper for parsing/serialization
	if len(middlewareChain) > 0 {
		b.WriteString("\thandler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	} else {
		b.WriteString("\treturn func(w http.ResponseWriter, r *http.Request) {\n")
	}

	// Generate handler body based on pattern
	body, err := g.generateHandlerBody(ctrl, handler, ctrlField)
	if err != nil {
		return "", err
	}
	b.WriteString(body)

	if len(middlewareChain) > 0 {
		b.WriteString("\t}))\n\n")

		// Apply middleware chain in reverse order (innermost first)
		for i := len(middlewareChain) - 1; i >= 0; i-- {
			mwFieldName := g.middlewareFieldName(middlewareChain[i])
			fmt.Fprintf(&b, "\thandler = container.middleware.%s(handler)\n", mwFieldName)
		}

		b.WriteString("\n\treturn handler.ServeHTTP\n")
	} else {
		b.WriteString("\t}\n")
	}

	b.WriteString("}\n\n")

	return b.String(), nil
}

// generateHandlerBody generates the body of a handler based on its pattern
func (g *Generator) generateHandlerBody(ctrl *scanner.Controller, handler *scanner.Handler, ctrlField string) (string, error) {
	sig := handler.Signature

	// Validate pattern
	if sig.Pattern != scanner.PatternResult && sig.Pattern != scanner.PatternRawHTTP {
		return "", fmt.Errorf("unsupported handler pattern: %s (only 'result' and 'raw_http' patterns are supported)", sig.Pattern)
	}

	data := map[string]any{
		"Controller":        ctrl,
		"Handler":           handler,
		"CtrlField":         ctrlField,
		"ValidationEnabled": g.validationCfg.Enabled,
	}

	// Use appropriate template based on pattern name
	templateName := sig.Pattern + ".tmpl"
	return g.executeTemplate(templateName, data)
}

// buildMiddlewareChain builds the ordered middleware chain for a handler
// New algorithm:
// 1. If @With explicit override → use only those
// 2. If @With none → no middleware
// 3. Otherwise → collect middleware where target=all OR target matches handler's/controller's tags
// 4. Sort by order, then file path, then line number
func (g *Generator) buildMiddlewareChain(ctrl *scanner.Controller, handler *scanner.Handler) []*scanner.Middleware {
	// Check for explicit @With override
	if len(handler.With) > 0 {
		// Check for "none" keyword
		if len(handler.With) == 1 && handler.With[0] == "none" {
			return nil
		}

		// Use explicit middleware list
		var chain []*scanner.Middleware
		middlewareMap := make(map[string]*scanner.Middleware)
		for _, mw := range g.project.Middleware {
			middlewareMap[mw.Name] = mw
		}

		for _, name := range handler.With {
			if mw, ok := middlewareMap[name]; ok {
				chain = append(chain, mw)
			}
		}

		// Sort by order (explicit With maintains order from annotation)
		return sortMiddleware(chain)
	}

	// Auto-target by tags: collect controller and handler tags
	allTags := make(map[string]bool)
	for _, tag := range ctrl.Tags {
		allTags[tag] = true
	}
	for _, tag := range handler.Tags {
		allTags[tag] = true
	}

	// Collect matching middleware
	var chain []*scanner.Middleware
	for _, mw := range g.project.Middleware {
		if g.middlewareMatches(mw, allTags) {
			chain = append(chain, mw)
		}
	}

	// Sort by order, file path, line number
	return sortMiddleware(chain)
}

// middlewareMatches checks if middleware targets match the given tags
func (g *Generator) middlewareMatches(mw *scanner.Middleware, tags map[string]bool) bool {
	// target=all always matches
	if mw.Target == "all" {
		return true
	}

	// Split comma-separated targets
	targets := strings.SplitSeq(mw.Target, ",")
	for target := range targets {
		target = strings.TrimSpace(target)
		if target == "all" || tags[target] {
			return true
		}
	}

	return false
}

// sortMiddleware sorts middleware by order (ascending), then file path, then line number
func sortMiddleware(middleware []*scanner.Middleware) []*scanner.Middleware {
	// Simple bubble sort (fine for small lists)
	sorted := make([]*scanner.Middleware, len(middleware))
	copy(sorted, middleware)

	for i := range sorted {
		for j := i + 1; j < len(sorted); j++ {
			if compareMiddleware(sorted[i], sorted[j]) > 0 {
				sorted[i], sorted[j] = sorted[j], sorted[i]
			}
		}
	}

	return sorted
}

// compareMiddleware compares two middleware for sorting
// Returns: -1 if a < b, 0 if a == b, 1 if a > b
func compareMiddleware(a, b *scanner.Middleware) int {
	// First: compare order
	if a.Order < b.Order {
		return -1
	}
	if a.Order > b.Order {
		return 1
	}

	// Second: compare file path
	if a.FilePath < b.FilePath {
		return -1
	}
	if a.FilePath > b.FilePath {
		return 1
	}

	// Third: compare line number
	if a.Position.Line < b.Position.Line {
		return -1
	}
	if a.Position.Line > b.Position.Line {
		return 1
	}

	return 0
}
