package generator

import (
	"fmt"
	"strings"

	"github.com/azizndao/glib/internal/scanner"
)

// generateRoutes generates the route registration code (routes.gen.go)
func (g *Generator) generateRoutes() (string, error) {
	var b strings.Builder

	// Package and imports
	b.WriteString("// Code generated by glib. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", g.pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString(")\n\n")

	// registerRoutes function
	b.WriteString("// registerRoutes registers all HTTP routes\n")
	b.WriteString("func registerRoutes(mux *http.ServeMux, c *container) error {\n")

	// Register each handler
	for _, ctrl := range g.project.Controllers {
		for _, handler := range ctrl.Handlers {
			g.generateRouteRegistration(&b, ctrl, handler)
		}
	}

	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	// applyMiddleware function
	b.WriteString("// applyMiddleware applies global middleware\n")
	b.WriteString("func applyMiddleware(handler http.Handler, c *container) http.Handler {\n")
	b.WriteString("\t// Apply global middleware here if needed\n")
	b.WriteString("\treturn handler\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// generateRouteRegistration generates registration for a single route
func (g *Generator) generateRouteRegistration(b *strings.Builder, ctrl *scanner.Controller, handler *scanner.Handler) {
	// Build the route pattern (Go 1.22+ format)
	pattern := fmt.Sprintf("%s %s", handler.Method, handler.FullPath)

	// Generate handler wrapper
	handlerName := g.handlerWrapperName(ctrl, handler)

	b.WriteString(fmt.Sprintf("\tmux.HandleFunc(\"%s\", %s(c))\n", pattern, handlerName))
}

// handlerWrapperName generates a unique name for handler wrapper
func (g *Generator) handlerWrapperName(ctrl *scanner.Controller, handler *scanner.Handler) string {
	return fmt.Sprintf("handle%s%s", ctrl.Name, handler.Name)
}
